image:
  repository: ghcr.io/joacofurlan/challenger-mindfactory
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: NodePort
  port: 80

redis:
  host: redis-service.default.svc.cluster.local
  port: 6379
