image:
  repository: ghcr.io/Joacofurlan/app
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: NodePort
  port: 80

redis:
  host: redis-service.default.svc.cluster.local
  port: 6379
