replicaCount: 3

image:
  repository: ghcr.io/joacofurlan/challenger-mindfactory
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

redis:
  host: test-redis-devops.rrr7yo.ng.0001.use1.cache.amazonaws.com
  port: 6379
