replicaCount: 3

image:
  repository: ghcr.io/joacofurlan/challenger-mindfactory
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

redis:
  host: clustercfg.test-redis-devops.fvaym2.use1.cache.amazonaws.com
  port: 6379
